name: Django CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_NAME: authdb
      DB_USER: django_user
      DB_PASSWORD: django_password
      DB_HOST: postgres
      DB_PORT: 5432

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: authdb
          POSTGRES_USER: django_user
          POSTGRES_PASSWORD: django_password
        ports:
          - 5432:5432


    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run migrations
        working-directory: cicd
        run: python manage.py migrate

      - name: Run test suite
        working-directory: cicd
        run: python manage.py test cicdapp
